cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm5QUlBUNzNJT3VveXczUm9wLXZ4Mmc3ZEc5Nkg0SDNjUndhMTBnSTlBblYyeDJWYVVr
    OTh0eUdZOWVRaWFQVXBBWV9fcFhBMlQweXNqcHlPSFdxMXp2MGFxUC1SUjU0OU9hNzItRFJqY1ZN
    bzNCbHNQLS1yZHh6aVZWb2VQWWpIeXVqekhnOFl2aVkzOFp3amJUSEQ2U21BQ2UzOC0xdXNwblZB
    djRkb2hqNm51X0R0dUZmbWpnb3pJeGRVdTNxWXVWWmFzZkVEb3RjcGdUbVpMdXZLaS1aYTNERFlu
    WDdkM1BQVlZiNll6NjlDc1NIQi1pUDA2dmxNNHpEZ2Z3SDRyUkdiNGx5enlBR3FSYkhVS21IOTdv
    S1NWeHg0TDJTLWp5Sm1pSGdkX1Q4Q0JzTWZlVGNNcW1iUW1vTUd5cU11UUg0SnFEUEtfUVV1eWhV
    M0NHM29iQ1Q0MFAwd2pNN1pFY3EySGROZkU2RHc3aW4yNGh4YWRmVG1mdTU0VU9EZ3hoRUtUUDR2
    a1lOSVFOeDVxRnRTV0FNOGRESE9rV2pLSHZoYUJyTVFzMUpYR3ZoUnJoaGZTQnpCWENjek1KN2ly
    TUxfT3FwNzZULXg5R3VVNTl6bHhQNW04enpNTFZ1RXVZYmNMcFFaMlZ6X0lxRTZFcjhsOC1LeWNN
    NHNNUEduX05iMmZOQjR2RDgwbnNhQjRxbzg4bFZheVRyX0IyT1g1cXo2TFpfVW82bHdoREtRLUVs
    SF9pdTNGSmIzcDlkMFNHOFd3ME1MUzNLSTBOU0V6QzdZTnNibnR2YVZEcEFoUWNyalpCdW5fcVJB
    Q1JMNVJQTnNPY3hTdFZqaE1fUGltelVRZHozeUNULXpza3M3Y29UUVFqR1E2N1E9PQ==
