cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm5ERFI0V2V5cGdTYnlmSzlsXzFuSFBCeGd4VWctYk1Od1BCRTFjWXpvcExQbHVoeWJD
    RnpmV0VaNkdZTHZKZFpLcVRjN3pxdjBmbWJaRnNQemhhaklWZ0dBY0tpaUpFSnR5bmJJLWsxMm5t
    ZXdZNWNnaVZwa1dOQzhOY1VpSVFzak9qaWdQMnFMV2M5bDB6XzEyVnNyRGZUeHBaajVlTGJpMFRJ
    RjIzUFBEdmZ6M0duaUtBUmduNExKZmpNcW9fYi1fb2V3YnMzNXlrTDJGR3UydlF5aHJPajNGUy14
    bnFuZGtjcWdMdjdWcVZ6YjNCMm9aSUs0bGtrbU40dTJrdzBhenpXak9aVjE2OW5ZNnJjZm13Y2NW
    TWNkOEhPRlhOQXItWTFoNXNGTGU1ZnRhSi03SWhXQUM4TmZNMWxmU2xab0hXcTFDTEdPdnJkbGQ2
    d2VXVjRvdDk4c2dlZHF4eHI0UU5HWnNBUEhld1dFNUdib2lyWjdNRlNnS3FUUGc0cTFMMktwVnpv
    VWpYMXozd0tMYlZfOWY1UHAtc2phcjJURWtacFlTUDhyU0lJTFA4QWk5cGg1ME1vOU5QekhQQWM4
    V3pvODgwZ2t5V0FVQnM0cmtpUjluaWhlbnFkNzl3T2c5eF9DMk1yblNiNXRTSXpScTFrb2p1QzhW
    MTMtTFJ3dDc4czRPbFZFUkszYmwxbkFYeDNRNENWSl95VklXU0lxWFdVV1pMYXZFRnBoZFhXaFZl
    Nm9vNkhzTEdFZlRZZjJ6czlIS1lha1pZTnEzdEdqOElYa0o1VWJKSzFCa3ZNRGN5cnNVa1pSX3BI
    enY4dGFjbHVVUkFPNmZTc2hBQlh0ejdRbVo0aXhldE1SWmd5R3hKQWRnVE95YVE9PQ==
