cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm5EcmgzNFFvazVTSTBkZTQ5LVhHVk44RjJ4Nm1HMTZQQjBqa3EzRnZYOWpWMnhFZU8y
    UFMyVkw3YVdHU2hnNlRBREFQcXNEek9QYTNHZ0gtNGl0ZjhpV28tX3BTSUxtNUZKM0RNQ2RpWHF0
    dXhZNkM5Z2lpWHNHdGRSa1VqS0hKVlJ4azZNSHZtQ1hFaFUtbHBuQXpKWW4ta0xvdnN0aGk1RlBY
    NHhkU19wa0wxYUdKcG1PVm1oeDdKZEhrMTNwRloyZTA5aElMVjdCbkhkanhXbFhQV29ISzlvZHpy
    V2d2cUEzNmxTT0J0ZlZSNTZ2OFpOTVBJeHN1UmxfS0ZNZ0xaMHVwNmtRZHJJS3pNR1RxSm5GNHZK
    ZnVWa0QyY044eVV1RDFUMDMtNE1qNUEwX2htU1hqQ2FnQTN3c09tcG1ZbU9SRnQxWHd4WUVGQ0di
    NE43NDUyY3NOOWpDaE9vM2N4MWI4UHA1ZXBtMEZFWllicWl2NmQ2R0J2RkQzYy1CTkFXbGJrR0Zv
    YVpKR1VJR2NZaFJGQTViUXlVZnVLbWF3OVQ2MTlTY0ZiOXl2aU5LTS1ORXZfMnJ5Q0F0NU92MkdS
    emFxZWt3RExxa3JQdTNFa0p2MkVJMWlRdk1vOVZ3RjdsWnlVNGpzYVFSaWZLNVpsbXpyMjUyR3FL
    c0VOekk1ZUVUOFFLc29yTXBGTWhYZUF5LURXN1M4T2xJUjNPOVNYSFZBR0RHVXF0N1EyeTBYY3Nt
    cUNiWVp0QnoyNGZxa243YkNEWVBiODR5R0dVa3V6RHBmUE5vaGtCbFdrYVB2MGVEZlIxYlJNRC1U
    QURGdURMaE12blMzdUo2TkNPd3lTWlhDaEo4RDVMXzFjTW1mVERzMW96U3k2c0E9PQ==
